### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ServerDeveloper9447** [is-a-dev/register#1168]
Your domain name: duck.is-a.dev

Explain any issues you are facing

https://glitch.com/help/kb/article/9-how-do-i-add-a-custom-domain-a-cname-or-a-record-for-my-custom-domain/

^ I can't understand how to. Can anyone please help me?

**Comment by leecheeyong** [comment]
> 
> 
> Your domain name: duck.is-a.dev
> 
> Explain any issues you are facing
> 
> https://glitch.com/help/kb/article/9-how-do-i-add-a-custom-domain-a-cname-or-a-record-for-my-custom-domain/
> 
> ^ I can't understand how to. Can anyone please help me?

First, seems like you've requested for duckdev.is-a.dev instead of duck.is-a.dev. If that's just a mistake, you may continue reading ...

Seems like you have everything setup correctly on this part ( domain requesting ), now you just have to link it with your glitch app.

1. create a glitch app if you haven't already.
2. find the custom domain button on your project page.
3. click the button and type in `duckdev.is-a.dev` or whatever you've requested for.
4. click link domain, I'm not sure if I've listed everything out, but that should be everything you need to know.
