### ISSUE TITLE
Privacy error

### ISSUE THREAD

**Issue by NotMyx** [is-a-dev/register#1266]
How do I enable HTTPS? It dosen't let me check the box.

**Comment by Satindar31** [comment]
wait for the checks to complete then click enforce HTTPS (assuming you use GitHub pages)

**Comment by givinghawk** [comment]
![Screenshot_20220407-214202_Chrome](https://user-images.githubusercontent.com/72263189/162317472-9f82bee9-7110-4aef-a823-03518d89fd55.jpg)

**Comment by phenax** [comment]
For github pages, sometimes the checkbox shows up as disabled. In this case, you need to remove your domain from the input, save it and then add it back again. The checkbox should re-appear.

@givinghawk, your issue is different since you're using an .xyz domain so you'll need to add your .is-a.dev subdomain to your ssl certificate. How to do that depends on what service you're using for hosting and you can look for a solution in their documentation.

**Comment by givinghawk** [comment]
> For github pages, sometimes the checkbox shows up as disabled. In this case, you need to remove your domain from the input, save it and then add it back again. The checkbox should re-appear.
> 
> @givinghawk, your issue is different since you're using an .xyz domain so you'll need to add your .is-a.dev subdomain to your ssl certificate. How to do that depends on what service you're using for hosting and you can look for a solution in their documentation.

do you have any links for the way to do that on cPanel?
