### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by WiseFrederick** [is-a-dev/register#13347]
### sebb.is-a.dev

I can't link this subdomain to Cloudflare, I have used the manual help thing and still can't get it to link, I have asked in the discord server and couldn't get any good support from anyone they just kept telling me to "read the fucking Manuel!" I cannot get this to work with Cloudflare and strongly suggest you make the Manuel clearer and invest on making a YouTube channel with videos on how to use the service. I have tried all possible ways on how to do it but still can't get it to work, I have waited more than 24 Hours and need some help, I have also tried manually making the subdomain but it still doesn't work.

Please reply asap!

**Comment by VaibhavSys** [comment]
I will assume that you are @bruhplaneguy from discord as that seems to be the most relatable recent conversation to the one which you are describing.

We cannot help you if you don't provide us with the details, we tried to ask you further questions in order to get more details about the issue which you are facing but you did not give us any details requested, we cannot help you like that.
