### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by N-Nilashan** [is-a-dev/register#13561]
![image](https://github.com/is-a-dev/register/assets/153603329/82325f51-076f-41e5-bbae-d5f9b119dfbf)

why I get this error?

**Comment by CuteDog5695** [comment]
> ![image](https://private-user-images.githubusercontent.com/153603329/324800454-82325f51-076f-41e5-bbae-d5f9b119dfbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzE0ODQsIm5iZiI6MTcxNDEzMTE4NCwicGF0aCI6Ii8xNTM2MDMzMjkvMzI0ODAwNDU0LTgyMzI1ZjUxLTA3NmYtNDFlNS1iYmFlLWQ1ZjliMTE5ZGZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMTMzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjM2MTcwMzU1ODZlOWJiMjU5ZTAzOWQwYzYxZTE1M2IxYjMyYzE2NGY2NDk2NWE4MjNhNWI1MDFiOWJkNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.om1hzJpazvV0zJXIIKOzP3FPXDIT9zH_afkweUqNUgQ)
> 
> why I get this error?

The is-a.dev domain you putted doesn't even exist, but you got nilashan.is-a.dev.
But even if you tried connecting nilashan.is-a.dev it wouldn't work since its using URL record (which is redirecting your domain) so you would have to change the record to the CNAME github gave you (n-nilashan.github.io)
