### ISSUE TITLE
DMCA Takedown Request for clay.is-a.dev

### ISSUE THREAD

**Issue by xytrux** [is-a-dev/register#14808]
### Domain
https://clay.is-a.dev/triaxis

### Reason
Plagiarizing on my research without crediting the source (me)

### Proof

The user is taking my research and claiming it as his.

Refer to these images (not in order):
![Screenshot_20240710-124538](https://github.com/is-a-dev/register/assets/79881161/807f9893-a167-47af-ae04-fd2146aabf48)
![Screenshot_20240710-124533](https://github.com/is-a-dev/register/assets/79881161/c6d8cb46-5204-4937-a652-0e65a1764c49)
![Screenshot_20240710-124816](https://github.com/is-a-dev/register/assets/79881161/c1fc5072-54d7-4e85-93ad-33a29d133a57)
![Screenshot_20240710-124812](https://github.com/is-a-dev/register/assets/79881161/c7653bc3-4aaf-4ab3-b2db-cd3902ac29f8)

![Screenshot_20240710-124820](https://github.com/is-a-dev/register/assets/79881161/6c9c67d2-01dc-4117-8157-48c29ef5327b)

![Screenshot_20240710-124823](https://github.com/is-a-dev/register/assets/79881161/db4b1f64-339b-4caf-896a-084b20f3fcc3)

![Screenshot_20240710-124836](https://github.com/is-a-dev/register/assets/79881161/ce5a24cb-8f63-40ad-a1c6-067c01b0800e)
![Screenshot_20240710-124832](https://github.com/is-a-dev/register/assets/79881161/cc1c5f35-c9bc-450f-9c07-72e06898bbeb)
![Screenshot_20240710-124829](https://github.com/is-a-dev/register/assets/79881161/d02fffaa-6837-41f7-8c68-1174d12c7f82)

![Screenshot_20240710-124956]
![Screenshot_20240710-124930](https://github.com/is-a-dev/register/assets/79881161/32a0d285-8478-4f4d-ad23-695a837ef4ef)
(https://github.com/is-a-dev/register/assets/79881161/48c8f2a6-e0cd-4911-b80b-4d9e013e7a4f)
![Screenshot_20240710-124933](https://github.com/is-a-dev/register/assets/79881161/dcac02eb-c23c-4382-a0d1-f3e4970f3493)

![Screenshot_20240710-124937~2](https://github.com/is-a-dev/register/assets/79881161/6b1e5523-8f16-4dfb-8e62-c36bf9824666)
![Screenshot_20240710-125000](https://github.com/is-a-dev/register/assets/79881161/f1a1ff64-db01-41a3-aaab-00f014c48c05)

![Screenshot_20240710-125016](https://github.com/is-a-dev/register/assets/79881161/a57a1cb8-86db-4249-ae90-e4958cb62018)
![Screenshot_20240710-125008](https://github.com/is-a-dev/register/assets/79881161/63991756-6f0c-46cf-ac96-90a2de64dda4)

**Comment by CuteDog5695** [comment]
So from what I understood, the owner of clay.is-a.dev made the site which you listed was giving info on a Geometry Dash player whilst using the info you found without permission. Since I see they are not complying in removing the site, we might remove the domain itself (as we have done before in #13650 which is DMCA related) and ban them from this service, though I will talk to the other maintainers of the service to see if we should remove the domain, which there is high chances. In the mean time, you can notify the user that the domain is at risk.
If you wish to give more proof that its your info, you can always contact me in discord (username is cutedog5695) so that you build a much stronger case for your side, thus making the domain more likely being taken down.

@ClaytonTDM I will give you 24hrs to resolve this issue, if the alleged stolen information hasn't been removed by then we might consider taking down your domain + banning you from this service (as we have done to others before).
If you wish to explain your side, you can also contact me on discord (once again, username is cutedog5695).

**Comment by ClaytonTDM** [comment]
i've sent you a dm on discord @CuteDog5695

**Comment by xytrux** [comment]
Closing as issue has been resolved.
