### ISSUE TITLE
Question about MX/txt

### ISSUE THREAD

**Issue by EpicGamer007** [is-a-dev/register#1647]
Hi, i have a question about MX/TXT records for email forwarding.

Links:

* https://forwardemail.net/en/faq#how-do-i-get-started-and-set-up-email-forwarding
* https://github.com/is-a-dev/register/blob/main/domains/abhay7.json
* https://abhay7.is-a.dev

Basically, I would like to add email forwarding to the subdomain I created. However, you outlined in https://github.com/is-a-dev/register/pull/1093 about how we could not use CNAME with MX records due to technical limitations.
I am a bit confused on what you mean by that, does that mean that if I want email forwarding with a custom domain, I would have to stop using a CNAME on it and instead use something like LINK if I want email forwarding? (I do not believe I can use A records because https://replit.com does not actually respond with the website when requested with the IP address)

Thanks

**Comment by phenax** [comment]
Yes. Unfortunately due to limitations in how DNS works, `CNAME` cannot be used along side other DNS records. I couldn't find any documentation about replit with `A` records so I'm assuming that isn't possible.
I haven't tried this myself but you could try routing it through a dns service to get an A record (give cloudflare a try). You could also use a URL redirection to your repl it (not ideal but does the job).

**Comment by EpicGamer007** [comment]
Thanks, I will be submitting a pr shortly with some changes to my current json file :)
