### ISSUE TITLE
Can I add copyright

### ISSUE THREAD

**Issue by Bad-Boy-Codes** [is-a-dev/register#1735]
i want to copyright my website 
can u put a copyright on it now then?
is the subdomain totally mine now?

my domain: badboy.is-a.dev

**Comment by phenax** [comment]
> i want to copyright my website
> can u put a copyright on it now then?
Copyrighting your websites contents has nothing to do with the subdomain itself

> is the subdomain totally mine now?
There is no real ownership with a subdomain since at the end of the day, the tld stays the "owner". However, for all intents and purposes, you do have full control over the the contents hosted on your subdomain (as long as it doesn't break our code of conduct).

**Comment by thetayloredman** [comment]
> There is no real ownership with a subdomain since at the end of the day, the tld stays the "owner". However, for all intents and purposes, you do have full control over the the contents hosted on your subdomain (as long as it doesn't break our code of conduct).

that's not a tld (top level domain), that's a domain. in this case, the "FQDN" is `badboy.is-a.dev`. The subdomain is `badboy`, the domain is `is-a`, and the top-level domain/TLD is `dev`.

**Comment by MaskDuck** [comment]
closed with author consent on discord
