### ISSUE TITLE
Having a MX and URL record leads to only MX in dns

### ISSUE THREAD

**Issue by RiskyMH** [is-a-dev/register#2365]
### Expected outcome
Having both MX and A record in DNS results 

### Observed outcome
Only MX record is shown in DNS result
(btw the evidence was in the thread mentioned in #2321 - but it was deleted)

ps. this was ages ago, but im only bothered to make an issue now

EDIT: I meant A not AAA

**Comment by mtgsquad** [comment]
AAAA isn't supported.

**Comment by phenax** [comment]
@RiskyMH, I can't find anywhere in [your file's](https://github.com/is-a-dev/register/blob/main/domains/riskymh.json) history where it was using A record. Can you link to a commit where you were using it? Also, could you try using it again so we can investigate if there is an issue here.

**Comment by RiskyMH** [comment]
> @RiskyMH, I can't find anywhere in [your file's](https://github.com/is-a-dev/register/blob/main/domains/riskymh.json) history where it was using A record. Can you link to a commit where you were using it? Also, could you try using it again so we can investigate if there is an issue here.

@phenax, I was never using an A record, I was using URL at that time (and still do). I only mentioned the A record because when you currently do a dig on it, it has an A record. But what I was trying to say is that what is currently visible when doing the command is removed when adding a MX record (only MX was there)

**Comment by phenax** [comment]
Something is definitely wrong here.

Since, URL redirections aren't DNS entries, what happens is when you have a URL record, it hits the wildcard A record pointing to our server, which then performs the redirection to the given url. MX records require an A record which is why we have the wildcard A for all subdomains. This worked when we initially rolled out MX but now this seems to be somewhat broken when using the wildcard. I'll speak with namecheap support and see if there were any changes made from their end. Maybe they're trying to be more spec compliant but if that is the case, it's terrible that we were not notified of those changes.

Anyways, thank you for bringing this to our attention, @RiskyMH! We really appretiate it. Will look into this issue and post any relavant updates here.

**Comment by phenax** [comment]
Had a conversation with namecheap support and that does seem like the case. I've explicitly added injecting explicit A record just for the MX+URL case. Will still need to run some more tests to see its impact and also maybe look for more conflicts like this. @RiskyMH, would really appreciate if you could test it our with an MX record on your domain.
