### ISSUE TITLE
Feedback/suggestion: Add NS records

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#2380]
Hi, I think it would be cool if you could add NS records, because then we can link them to DNS hosts and things. So we don't have to make a PR everytime.

**Comment by phenax** [comment]
The api we use to manage this service does not support NS records. This was also discussed [here](https://github.com/is-a-dev/register/issues/394).
Even if it were supported, I think NS in is-a-dev is a no-go because any abuse of the service goes completely unchecked. Part of the reason why we need a pr is because we need to review what is being linked to our service. Anything that goes against our code of conduct is reject in reviews.

Closing this as we're not planning on supporting NS
