### ISSUE TITLE
Support: Vercel.app custom subdomain issue

### ISSUE THREAD

**Issue by tharindusathis** [is-a-dev/register#249]
Can we use this custom domain on Vercel? 
I was trying to add `tharindu.is-a.dev` #188 to a Vercel app which is deployed in http://tharindu.vercel.app, but get the following error, that "domain tharindu.is-a.dev is already owned by another Vercel account.". 
![image](https://user-images.githubusercontent.com/34299693/95962525-19d60500-0e24-11eb-9062-2b1ca3f0a58e.png)

Cannot we use this with Vercel or is there any workaround for it?

**Comment by phenax** [comment]
It seems like they have restrictions for subdomains. Not sure why.

I've found 2 issues there that seem to be related to this - 
* https://github.com/vercel/vercel/issues/3671
* https://github.com/vercel/vercel/issues/3513

But neither of them have a proper resolution.

I'd suggest creating a new issue there.
If they can't help then it does seem like you can't use vercel with is-a-dev subdomains.
Link the issue here so that I can document this problem for anyone else using vercel.

**Comment by tharindusathis** [comment]
https://github.com/vercel/vercel/discussions/5292

**Comment by phenax** [comment]
I've found this other discussion here -> https://github.com/vercel/vercel/discussions/4859
Seems like you could give this a try. Lemme know how it goes.

**Comment by phenax** [comment]
I've found this other discussion here -> https://github.com/vercel/vercel/discussions/4859
Seems like you could give this a try. Lemme know if it helps

**Comment by tharindusathis** [comment]
Reply for the support ticket by Vercel is saying that,

> **The is-a.dev domain is indeed owned by another account on Vercel.**
> **If you believe this be incorrect, can you provide proof of ownership?**

I think that its means may be is-a-dev is using Vercel under that hood? Is it? 

Note: Normally , if someone owns the domain `abc.com` on Vercel lists all the subdomain `xxx.abc.com` as owned by him/her.

**Comment by phenax** [comment]
is-a-dev doesn't use vercel in any way. I think someone else added their `user.is-a.dev` subdomain to vercel. If there is no way around this, you can use is-a-dev to URL redirect to your `.vercel.app` website instead. Not the best way to do it but it doesn't seem like vercel is willing to play ball.

**Comment by tharindusathis** [comment]
Yeah redirecting would be also a fair workaround.  

For the time being I could see only one other Vercel domains except #83 which is assigned the record https://ezedin.is-a.dev. I don't know whether @ezedinff has succeeded this step. Hi @ezedinff, can you please let us know did you succeed?

**Comment by sycured** [comment]
I've the same problem but I thought that it was a 302 redirect and not another type of redirect

**Comment by phenax** [comment]
@sycured, you are using a url redirection (which is a 301 redirection). This issue is related to CNAME records pointing to `.vercel.app`. If you are having any problems with your subdomain, you can create a new issue.

**Comment by phenax** [comment]
@tharindusathis, my guess is that @ezedinff added his subdomain (`ezedinff.is-a.dev`) and this locked the `is-a.dev` domain to his account preventing anyone else from adding their subdomains due to the weird laws that vercel made up about subdomains. If that is the case, that I don't think CNAME records are usable by vercel apps. I would like a confirmation on this so that this issue is documented.

**Comment by tharindusathis** [comment]
@phenax I was also thinking the same. But as `ezedinff.is-a.dev` is not alive yet, therefore it seems that @ezedinff is also not succeeded yet.

And the support ticket update from Vercel says:
> If an is-a.dev domain is being used on Vercel by another account, it will not be possible to use a subdomain on another.
> We are working on changes to this system for the future.

**Comment by phenax** [comment]
I'm closing this issue for now. Will be updating the docs soon.
