### ISSUE TITLE
Can I use a is-a.dev subdomain as a minecraft server IP/url?

### ISSUE THREAD

**Issue by DaInfLoop** [is-a-dev/register#2810]

**Comment by MouseMoosz** [comment]
https://github.com/is-a-dev/register/pull/2811#issuecomment-1183055522

**Comment by mtgsquad** [comment]
You cannot use NS records, with is-a.dev, and we do not support SRV either, however what you could do is create an A record pointing to the IP of the server, and if the port of your server is the default for minecraft people should directly be able to connect, otherwise you may have to add a port after that, however it is possible.

**Comment by omxpro** [comment]
@phenax this should be closed too.
