### ISSUE TITLE
Sarnax is SCAMMER 

### ISSUE THREAD

**Issue by Eneshunter** [is-a-dev/register#3221]
Domain you want to report: 
sarnax scammed me

### Reason
Explain why you think this domain is being abused
I have proof. People like this shouldn't have a place on this site.

**Comment by Eneshunter** [comment]
I will send the evidence to those who want it

**Comment by phenax** [comment]
He's banned on this service. Please explain what this has to do with is-a-dev or specify the .is-a.dev sub-domain he used.
Your description of the issue is useless. Not only did you not take the time to specify the subdomain, but you didn't even tag the user you're complaining about. If this was a pointless spam, you're getting banned as well.

**Comment by Eneshunter** [comment]
> Domain you want to report: @SarnaxLii  scammed me
> 
> ### Reason
> Explain why you think this domain is being abused I have proof. People like this shouldn't have a place on this site.

**Comment by phenax** [comment]
Again, please explain how that has anything to do with is-a.dev?

**Comment by andrewstech** [comment]
> I will send the evidence to those who want it

Send your evidence here or you can email andrew@win11react.com and it will be shared privately with the other maintainers.

**Comment by phenax** [comment]
@andrewstech, sarnax was banned from this service. Unless he has a sub-domain here created with a separate account, this person is just trying to waste our time.
