### ISSUE TITLE
Support needed for GitLab Pages site

### ISSUE THREAD

**Issue by avinal** [is-a-dev/register#404]
Your domain name: avinal.is-a.dev

Explain any issues you are facing

GitLab Pages is asking for verification before the domain is enabled. Asking to add a CNAME record and a TXT record
![image](https://user-images.githubusercontent.com/74113200/99036242-4dcd5300-25a7-11eb-9b2b-1fe71852d362.png)

I don't know what exactly needs to be done. Please Help.

**Comment by phenax** [comment]
The verification procedure for gitlab requires you to add a TXT record but that is not possible as DNS spec doesn't allow CNAME record to be specified with any other record. I'd suggest creating a new PR removing the CNAME record and adding a TXT record with the verification value. After that it merged and published, verify ownership on gitlab. Once, that is done, create another PR adding your CNAME record back and removing the TXT record.
This will be a bit annoying to get working. Seems like an overkill on gitlabs part.

Alternatively, you could just use a simple URL redirection instead of a CNAME record. Much easier and will not need any configuring on gitlab's end.
```
"URL": "https://avinal.gitlab.io"
```

**Comment by avinal** [comment]
Redirection seems like better option,  can I change my url to github pages, I will move my site there. Sorry for the inconvenience.

**Comment by phenax** [comment]
If you are gonna move to github pages then creating a CNAME would be much easier. Github doesn't need any verification.

**Comment by avinal** [comment]
I have added a pr. Thanks a lot 😄

**Comment by phenax** [comment]
Closing this for now. You can create a new one if you run into any other issue.
