### ISSUE TITLE
Make TXT records an array

### ISSUE THREAD

**Issue by DEV-DIBSTER** [is-a-dev/register#4773]
Suggestion: Ability to add additional TXT records for a domain, similar setup to A records. Multiple strings stored in an array.

**Comment by WilliamDavidHarrison** [comment]
I was thinking of adding this myself lol

**Comment by DEV-DIBSTER** [comment]
@WilliamDavidHarrison 👀

**Comment by VaibhavSys** [comment]
bump

**Comment by WilliamDavidHarrison** [comment]
@DEV-DIBSTER I'm not familiar with the scripts, and I feel like it would be too complicated to update all user domains to arrays, which would also break a bunch of things made for is-a.dev like the CLI, API, etc.

**Comment by DEV-DIBSTER** [comment]
Sounds good!

**Comment by WilliamDavidHarrison** [comment]
> We can allow both arrays and single TXT records so we won't have to run a migration for the existing records.

I can make a simple script which migrates all of them to arrays. This would be good because it would make the change to https://data.is-a.dev easier and also reduce the amount of code to do this.

**Comment by DEV-DIBSTER** [comment]
We could potentially do this. My only concern is with the dashboard and I think CLI, would this result in changes to that? I'd say probably.

**Comment by phenax** [comment]
The problem here wouldn't be writing the migration script itself. Ideally, any changes made to the records should be from the owners of those records. Migrations pollute that. Which is why I'd lean a little more towards TXT records being allowed in both forms.

Also, we'll have to make changes to the tools anyway since we are going to be allowing TXT's to be an array so I don't see a reason why one alternative is much different than the other.

**Comment by WilliamDavidHarrison** [comment]
Sounds good, whatever you think.
