### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by avcado** [is-a-dev/register#570]
Your domain name: avcado.is-a.dev

Explain any issues you are facing
Can't visit website. Firefox shows this:
![image](https://user-images.githubusercontent.com/77250184/107866354-7e868800-6e35-11eb-8e0e-86d2b6bba3e7.png)

When going to my site, i get this:
![image](https://user-images.githubusercontent.com/77250184/107866362-b097ea00-6e35-11eb-946d-1b0b25e6eb86.png)

**Comment by phenax** [comment]
Seems like you've misconfigured the repo. The record was created with a URL redirection record but the repo has been configured for a CNAME subdomain. If you meant to use a URL redirection record, you should unset the custom domain setting from the repo. If you meant to use a CNAME subdomain record, create a new pr with the following record - `"CNAME": "avcado.github.io"` instead of the URL record.
