### ISSUE TITLE
Merge AstroDNS and is-a-dev

### ISSUE THREAD

**Issue by TlochstaDev** [is-a-dev/register#5728]
Hi! I'm the founder of AstroDNS. ([click here for link](https://dns.tlochsta.net))
I think you should connect your domain is-a.dev because its easier to use the AstroDNS control panel then the GitHub pull requests. [your dns records must be hosted on cloudflare]
**What is AstroDNS?**
Welcome to AstroDNS, the go-to platform for easy and hassle-free subdomain creation. With AstroDNS, you can effortlessly obtain free subdomains and manage your DNS records to suit your needs. Register an account, personalize your subdomains, and enjoy our user-friendly interface. We provide comprehensive DNS management tools, high security, and reliable performance. Please note that AstroDNS offers free subdomains and does not support connecting your own domain. Experience the simplicity of AstroDNS today and unlock the full potential of your online presence.

**Comment by WilliamDavidHarrison** [comment]
Sorry, we cannot allow this due to a few reasons:
- Moving all the records over would be a massive hassle
- Using GitHub is easier as we can get more recognition and many people are already familiar with it
- We don't use Cloudflare, we use Namecheap DNS, due to Cloudflare's DNS record limit
- We don't want our users to have to create an account just to use is-a.dev, they should be able to use an account they already have (in this case, GitHub)
- Also, we have never heard of the service either and do not know its limitations and security risks

**Comment by TlochstaDev** [comment]
ok
