### ISSUE TITLE
Feedback/suggestion

### ISSUE THREAD

**Issue by joeleeofficial** [is-a-dev/register#846]
its hard to say, sometimes people may use the domain for malicious purposes. for example a replit project, maintainers can't tell what kind of project that is until it was merged and linked to the domain. I suggest maintainers to ask for a project url/link from contributors before merging

**Comment by joeleeofficial** [comment]
i found out that people can actually link their other replit account's projects using the same CNAME given. means there's going to be something like domain stealing.

**Comment by phenax** [comment]
@joeleeofficial, that's a good idea. @is-a-dev/maintainers, please take a note. We can add this to our docs as well

**Comment by joeleeofficial** [comment]
I think having that on [readme.md](https://github.com/is-a-dev/register/blob/main/README.md) is even better. I think its also good to add something like **requirements** on that as well. https://github.com/js-org/js.org/wiki/No-Content is a good reference.

**Comment by joeleeofficial** [comment]
I love how everyone can use **is-a-dev** for anything. Personal blog, discord bots and more... really cool !

**Comment by joeleeofficial** [comment]
> @joeleeofficial, that's a good idea. @is-a-dev/maintainers, please take a note. We can add this to our docs as well

Wiki is good, why not just use it ? The docs is kinda messy.

**Comment by phenax** [comment]
@joeleeofficial, wiki is hard to version control, so tracking edits become difficult for a team. Also, adding it to the readme is not a good idea because we don't want to overload the user with instructions and nuances on the first look. Keeping it one link away seems to be the right call. We should however work on cleaning up the docs as it is a bit hard to traverse through at the moment. Thank you for the suggestions.
Closing this issue as it has been acknowledged and is not immediately actionable.
